angular.module('publications.controllers')
.controller('WordleController', 
	function($scope, $state) {

		$scope.words = [
			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },
			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },
			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },

						{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },			{text: 'kupa',    size: 50 },
			{text: 'chuj',    size: 90 },
			{text: 'i',       size: 120 },
			{text: 'kamieni', size: 66 },
			{text: 'dupa',    size: 75 },
		];

	}
);